# Generated by Django 3.2 on 2021-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('users', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
