# Generated by Django 3.2 on 2021-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='task_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='users',
            field=models.CharField(max_length=20),
        ),
    ]
